version: '3.8'

services:
  app:
    build:
      context: .
    container_name: ehr-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ehrdb
      SPRING_DATASOURCE_USERNAME: ehruser
      SPRING_DATASOURCE_PASSWORD: ehrpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
  
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ehrdb
      POSTGRES_USER: ehruser
      POSTGRES_PASSWORD: ehrpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
