spring:
  data:
    rest:
      detection-strategy: annotated
      base-path: /api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
web:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
